# Site settings
title: Adventures in a kitchen
email: your-email@domain.com
description: "Just my musings about tinkering in my kitchen."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: chris_carpenter
github_username:  chrisncarpenter

# Build settings
markdown: kramdown
permalink: pretty
