# Site settings
title: Adventures in a kitchen
email: your-email@domain.com
description: "A collection of recipes that have come from inspiration, observation or reproduction. Sometimes a recipe will just arrive from the ether, other times I’ll eat something truly wonderful and I endeavour to reproduce the dish at home. Other times I’ll consult a cookbook for something tasty to eat."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: chris_carpenter
github_username:  chrisncarpenter
category_dir : recipes

# Build settings
markdown: kramdown
permalink: pretty
